# Generated by Django 3.2.23 on 2023-12-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
