# Generated by Django 3.2.23 on 2023-12-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
