# Generated by Django 3.2.23 on 2023-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_alter_student_age'),
        ('checkout', '0002_auto_20231210_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='students',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='students',
            field=models.ManyToManyField(blank=True, to='lessons.Student'),
        ),
    ]
