# Generated by Django 3.2.23 on 2023-12-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
