# Generated by Django 3.2.23 on 2023-12-19 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
         ('lessons', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_capacity', models.IntegerField(default=0, editable=False, null=True)),
                ('date_time', models.DateTimeField()),
                ('kit_req', models.IntegerField(default=0, null=True)),
                ('students', models.ManyToManyField(blank=True, to='lessons.Student')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lessons.lessontype')),
            ],
        ),
    ]
