# Generated by Django 3.2.23 on 2023-12-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontype',
            options={'verbose_name_plural': 'Lesson Types'},
        ),
        migrations.AlterModelOptions(
            name='liftpass',
            options={'verbose_name_plural': 'Lift Pass'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(to='lessons.Student'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='discipline',
            field=models.CharField(help_text='Ski or Snowboard', max_length=128),
        ),
    ]
