# Generated by Django 3.2.23 on 2023-12-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20231203_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='dateTime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='kitReq',
            new_name='kit_req',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='liftPass',
            new_name='lift_pass',
        ),
        migrations.RenameField(
            model_name='lessontype',
            old_name='ageRange',
            new_name='age_range',
        ),
        migrations.RenameField(
            model_name='lessontype',
            old_name='maxCapacity',
            new_name='max_capacity',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='Type',
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_type', to='lessons.lessontype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='discipline',
            field=models.CharField(help_text='Select Ski or Snowboard', max_length=128),
        ),
    ]
