# Generated by Django 3.2.23 on 2023-12-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontype',
            name='brief_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
