# Generated by Django 3.2.23 on 2023-12-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessontype_brief_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontype',
            name='brief_description',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
