# Generated by Django 3.2.23 on 2023-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20231203_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontype',
            name='level',
            field=models.CharField(default='unselected', help_text='Beginner, Intermediate, Advanced', max_length=128),
        ),
    ]
