# Generated by Django 3.2.23 on 2023-12-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20231203_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontype',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='unselected', max_length=128),
        ),
    ]
