# Generated by Django 3.2.23 on 2023-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_lessontype_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontype',
            name='age_range',
            field=models.CharField(choices=[('Child', 'Child'), ('Adult', 'Adult')], max_length=128),
        ),
    ]
