# Generated by Django 3.2.23 on 2023-12-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_lesson_places_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='places_taken',
            new_name='remaining_capacity',
        ),
    ]
