# Generated by Django 3.2.23 on 2023-12-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0013_rename_places_taken_lesson_remaining_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='userAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
