# Generated by Django 3.2.23 on 2023-12-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_alter_student_age'),
    ]

    operations = [
         migrations.AddField(
            model_name='lesson',
            name='dob',
            field=models.DateField(),
        ),
    ]
