# Generated by Django 3.2.23 on 2023-12-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_rename_age_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lift_pass',
        ),
        migrations.DeleteModel(
            name='LiftPass',
        ),
    ]
